version: "3"

volumes:
  mongo_data:
  mongo_backup:
  node_logs:
  media_data:

networks:
  app-network:
    driver: bridge

services:
  backend:
    restart: on-failure
    container_name: <%=project_slug%>_node_prod
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - /home/app/<%=project_slug%>/node_modules
      - node_logs:/home/app/<%=project_slug%>/logs
      - media_data:/home/app/<%=project_slug%>/uploads
    depends_on:
      - mongo
    networks:
      - app-network

    # tty: true
  mongo:
    restart: always
    image: mongo:4.2
    container_name: <%=project_slug%>_mongo_prod
    env_file:
      - .env
    command: mongod --port 37017 --storageEngine wiredTiger
    volumes:
      - mongo_data:/data/db
      - mongo_backup:/data/backup
    ports:
      - "37017:37017"
    networks:
      - app-network

  nginx:
    restart: always
    build: ./compose/nginx
    container_name: <%=project_slug%>_nginx_prod
    depends_on:
      - node
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

